apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: apps
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/jezielmoura/webhook:${GITHUB_SHA}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: webhook-config
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
      imagePullSecrets:
            - name: ghcr
---

apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: apps
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: webhook
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook
  namespace: apps
spec:
  rules:
    - host: webhook.nett.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  webhook
                port:
                  number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
  namespace: apps
  labels:
    app: webhook
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector.monitoring:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
