name: release
on:
  pull_request:
    branches: [ releases/* ]
  push:
    branches: [ releases/* ]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: setup
      uses: docker/setup-buildx-action@v3

    - name: login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/jezielmoura/webhook:${{ github.sha }}
        context: .
        push: true

    - name: set image sha
      run: envsubst < deployment.yaml > deployment-updated.yaml
      env:
        GITHUB_SHA: ${{ github.sha }}

    - name: deploy
      run: kubectl apply -f deployment-updated.yaml

    - name: restart
      run: |
        kubectl rollout restart deployment webhook -n apps
